### ISSUE TITLE
Do you have more instructions?

### ISSUE THREAD

**Issue by FrightRisk** [markatk/dcc-quality-analyzer#1]
Hello. Was not sure how to contact you. Do you have more detailed instructions or pictures on how to use this? On an Arduino Uno, DCC++ outputs on pin 10 for the main track. Do I connect pin 2 of the arduino running this quality analyzer to pin 10 of my DCC++ Base Station? And then output just goes to the serial monitor running on my laptop? Why are there two folders? One has the .ino sketch and the other has "cargo" files and  .rs files. Thank you!

**Comment by markatk** [comment]
Hi, this project is in development, but it does work already in some ways. I will write some instructions, but some stuff will change. Just a quick explanation: The project reads a dcc signal with the Arduino with some dcc shield and transmits the received data via usb to the pc, on which a host program is running, analysing and displaying the data, error rates etc.

Just a warning: Do not try to connect your Arduino directly to any dcc booster signal, or you will likely kill it.

**Comment by markatk** [comment]
I have added some more explanation in the README.md with c228f05. When I have time I will also add automated releases of the host program so you don't have to compile it yourself.
